### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by EjPlatzer** [gordon-cs/gordon-360-ui#1406]
# What and Why?

This issue proposes and tracks a migration of the 360 UI from JavaScript to TypeScript. TypeScript is a superset of JavaScript that adds static typing syntax. TypeScript compiles to JavaScript at build time, after running type-correctness checks that catch many insidious JavaScript bugs. This provides type-safety, more helpful Intellisense, and better self-documenting code. For more information, visit the [TypeScript website](https://www.typescriptlang.org/) and read about [Why TypeScript](https://www.typescriptlang.org/why-create-typescript).

The main goals of this migration are to:
- prevent, discover, and eliminate bugs by:
  - revealing TypeErrors at build time (e.g. calling `.length` on an object with no `length` property)
  - documenting data types in accordance with the API types, catching inconsistencies
  - ensuring that changes in one place result in the correct changes in all dependent code
- increase the capabilities of Intellisense, type hinting, and other Developer Experience tools
- reduce the boilerplate of JSDoc typing, allowing JSDoc comments to specify only important context/additional info

# How?
Incrementally. TypeScript can be enabled on a per-file (or even more granular) basis, which enables us to migrate only the most important parts of the app first, and immediately reap the benefits of doing so. As such, I have divided the migration effort into roughly 5 phases. The phases are split by conceptual piece of the app, and are not equal in breadth or complexity.

## Phases

I propose to migrate to TypeScript in these 5 general phases, ordered according to what will give the greatest benefit for the least effort:
- [ ] Phase 1: Migrate all services, along with necessary dependencies
- [ ] Phase 2: Migrate Contexts and hooks
- [ ] Phase 3: Migrate `src/components` shared components
- [ ] Phase 4: Migrate PWA code in `public` folder
- [ ] Phase 5: Migrate `src/views` single-use components

### Phase 1

The services cover 90% of the data types in use throughout our app, since they are solely responsible for fetching data from the API and other external data sources. By getting these data types statically determined and clearly documented, we increase the typed-ness of the rest of the app markedly for very little effort. TypeScript will be able to infer the types of most state, props, etc. based on the data passed in. 

### Phase 2

Contexts and hooks also affect data flow and they are relatively more complex than the rest of the app. However, they contain very little code, so correctly typing them will be not much work but can improve Developer Experience drastically, especially for less-experienced developers.

### Phase 3

The shared components are intended to be reused often. Having a well-documented, strongly-typed API makes them easier to use and harder to use incorrectly

### Phase 4

The PWA code interacts the least with the rest of the codebase. However, it is the source of our most insidious bugs because it deals so heavily in caching, message-passing, and other browser complexity. A well-designed typing could improve the clarity, correctness, and maintainability of the PWA code significantly.

### Phase 5

The final phase is a significant amount of work, but with the least long-term gain.The components in `src/views` are all single-purpose components used only once. While they would still benefit from the migration, especially in terms of Developer Experience and maintainability, the net gain would be much less since these are used/changed less often than the above.

**Comment by russtuck** [comment]
I am so excited you are doing this!  Great writeup and plan!

**Comment by dli505** [comment]
https://github.com/gordon-cs/gordon-360-ui/pull/2263

**Comment by dli505** [comment]
Part 1 of Components Migration: https://github.com/gordon-cs/gordon-360-ui/pull/2290
